# Site settings
baseurl:            ""
url:                "http://localhost"
panorama:           "right"

# Build settings
markdown:           kramdown
destination:        build
exclude:            [.DS_Store, .gitignore]
collections:
  hotspots:
    output:         false
