# Site settings
baseurl:            ""
url:                "http://localhost"

# Build settings
markdown:           kramdown
destination:        build
exclude:            [.DS_Store, .gitignore, node_modules]
collections:
  hotspots:
    output:         false
